[theme]
base = "dark"
primaryColor = "#1E88E5"
backgroundColor = "#090D14"
secondaryBackgroundColor = "#111722"
textColor = "#F5F7FA"
font = "sans-serif"

[server]
headless = true
maxUploadSize = 6
maxMessageSize = 50
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
